openapi: 3.0.3
info:
  title: ORGiD migration backend server
  description: >-
    This is the interface documentation for the RESTful API interface for
    backend services of ORGiD migration backend server
  version: 0.0.1
servers:
  - url: http://localhost:3333/api
    description: Local Testing server
paths:
  /ping:
    get:
      description: Ping-pong
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /owner/{address}:
    get:
      description: Returns list of owned ORGiDs DIDs
      parameters:
        - in: path
          name: address
          required: true
          schema:
            $ref: '#/components/schemas/EthAddress'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dids'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      description: Objet describing an error
      type: object
      required:
        - message
      properties:
        message:
          description: Error message
          type: string
          example: Something went wrong
    Pong:
      description: Ping-pong response
      type: object
      properties:
        time:
          type: string
          format: date-time
          example: '2022-11-16T22:33:49.333+01:00'
    EthAddress:
      description: EOA
      type: string
      pattern: ^0x[a-fA-F0-9]{40}$
      example: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
    Did:
      description: ORGiD DID
      type: string
      pattern: ^did:orgid:([0-9])*(?::)?(0x[a-fA-F0-9]{64})+$
      example: did:orgid:77:0xeae18b4ccf6dfd743dc1738c6547bc829c3384bcc2b48f98f0c9a49c5c67b2be
    Dids:
      description: List of ORGiDs DIDs
      type: array
      items:
        $ref: '#/components/schemas/Did'
